#/bin/bash
echo `./updater.sh`
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`
sleep 2s
echo `./updater.sh`
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`
sleep 2s
sleep 2s
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`
sleep 2s
echo `./updater.sh`
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`
sleep 2s
sleep 2s
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`
sleep 2s
echo `./updater.sh`
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`
sleep 2s
echo `./updater.sh`
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`
sleep 2s
echo `./watcher.sh`

